name: review_tool
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.72.0
  freezed_annotation: ^2.2.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  cached_network_image: ^3.2.3
  timeago: ^3.4.0
  dev_icons: ^1.0.0
  flutter_markdown: ^0.6.14
  shared_preferences: ^2.0.20
  collection: ^1.17.0
  flutter_highlight: ^0.7.0
  shimmer: ^2.0.0
  settings_ui: ^2.0.2
  uuid: ^3.0.7
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  freezed: ^2.3.2
  ffigen: 7.2.7

flutter:
  uses-material-design: true
